2018-12-25 10:01:00  [ pool-1-thread-1:0 ] - [ INFO ]  {dataSource-1} inited
2018-12-25 10:01:07  [ pool-1-thread-1:7286 ] - [ ERROR ]  发送失败
2018-12-25 10:01:07  [ pool-1-thread-1:7287 ] - [ ERROR ]  Couldn't connect to host, port: smtp.163.com, 25; timeout -1
2018-12-25 10:01:07  [ pool-1-thread-1:7302 ] - [ ERROR ]  发送失败
2018-12-25 10:01:07  [ pool-1-thread-1:7302 ] - [ ERROR ]  Couldn't connect to host, port: smtp.163.com, 25; timeout -1
2018-12-25 10:02:02  [ pool-1-thread-1:62064 ] - [ ERROR ]  发送失败
2018-12-25 10:02:02  [ pool-1-thread-1:62064 ] - [ ERROR ]  Couldn't connect to host, port: smtp.163.com, 25; timeout -1
2018-12-25 10:02:02  [ pool-1-thread-1:62074 ] - [ ERROR ]  发送失败
2018-12-25 10:02:02  [ pool-1-thread-1:62074 ] - [ ERROR ]  Couldn't connect to host, port: smtp.163.com, 25; timeout -1
2018-12-25 10:04:00  [ pool-1-thread-1:0 ] - [ INFO ]  {dataSource-1} inited
2018-12-25 10:04:00  [ Druid-ConnectionPool-Create-345197249:338 ] - [ ERROR ]  create connection error, url: jdbc:mysql://192.168.120.244:3306/aes?characterEncoding=utf-8, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'JackWei' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1425)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1481)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1998)
2018-12-25 10:04:00  [ Druid-ConnectionPool-Create-345197249:378 ] - [ ERROR ]  create connection error, url: jdbc:mysql://192.168.120.244:3306/aes?characterEncoding=utf-8, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'JackWei' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1425)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1481)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1998)
2018-12-25 10:04:00  [ Druid-ConnectionPool-Create-345197249:381 ] - [ ERROR ]  create connection error, url: jdbc:mysql://192.168.120.244:3306/aes?characterEncoding=utf-8, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'JackWei' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1425)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1481)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1998)
2018-12-25 10:04:00  [ Druid-ConnectionPool-Create-345197249:385 ] - [ ERROR ]  create connection error, url: jdbc:mysql://192.168.120.244:3306/aes?characterEncoding=utf-8, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'JackWei' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1425)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1481)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1998)
2018-12-25 10:04:00  [ Druid-ConnectionPool-Create-345197249:392 ] - [ ERROR ]  create connection error, url: jdbc:mysql://192.168.120.244:3306/aes?characterEncoding=utf-8, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'JackWei' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1425)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1481)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1998)
2018-12-25 10:04:00  [ Druid-ConnectionPool-Create-345197249:395 ] - [ ERROR ]  create connection error, url: jdbc:mysql://192.168.120.244:3306/aes?characterEncoding=utf-8, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'JackWei' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1425)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1481)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1998)
2018-12-25 10:04:00  [ Druid-ConnectionPool-Create-345197249:397 ] - [ ERROR ]  create connection error, url: jdbc:mysql://192.168.120.244:3306/aes?characterEncoding=utf-8, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'JackWei' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1425)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1481)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1998)
2018-12-25 10:04:00  [ Druid-ConnectionPool-Create-345197249:400 ] - [ ERROR ]  create connection error, url: jdbc:mysql://192.168.120.244:3306/aes?characterEncoding=utf-8, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'JackWei' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1425)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1481)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1998)
2018-12-25 10:04:00  [ Druid-ConnectionPool-Create-345197249:403 ] - [ ERROR ]  create connection error, url: jdbc:mysql://192.168.120.244:3306/aes?characterEncoding=utf-8, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'JackWei' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1425)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1481)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1998)
2018-12-25 10:04:00  [ Druid-ConnectionPool-Create-345197249:409 ] - [ ERROR ]  create connection error, url: jdbc:mysql://192.168.120.244:3306/aes?characterEncoding=utf-8, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'JackWei' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1425)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1481)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1998)
2018-12-25 10:04:00  [ Druid-ConnectionPool-Create-345197249:412 ] - [ ERROR ]  create connection error, url: jdbc:mysql://192.168.120.244:3306/aes?characterEncoding=utf-8, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'JackWei' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1425)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1481)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1998)
2018-12-25 10:04:00  [ Druid-ConnectionPool-Create-345197249:414 ] - [ ERROR ]  create connection error, url: jdbc:mysql://192.168.120.244:3306/aes?characterEncoding=utf-8, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'JackWei' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1425)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1481)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1998)
2018-12-25 10:04:00  [ Druid-ConnectionPool-Create-345197249:416 ] - [ ERROR ]  create connection error, url: jdbc:mysql://192.168.120.244:3306/aes?characterEncoding=utf-8, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'JackWei' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1425)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1481)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1998)
2018-12-25 10:04:00  [ Druid-ConnectionPool-Create-345197249:418 ] - [ ERROR ]  create connection error, url: jdbc:mysql://192.168.120.244:3306/aes?characterEncoding=utf-8, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'JackWei' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1425)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1481)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1998)
2018-12-25 10:04:00  [ Druid-ConnectionPool-Create-345197249:425 ] - [ ERROR ]  create connection error, url: jdbc:mysql://192.168.120.244:3306/aes?characterEncoding=utf-8, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'JackWei' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1425)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1481)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1998)
2018-12-25 10:04:00  [ Druid-ConnectionPool-Create-345197249:430 ] - [ ERROR ]  create connection error, url: jdbc:mysql://192.168.120.244:3306/aes?characterEncoding=utf-8, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'JackWei' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1425)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1481)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1998)
2018-12-25 10:04:00  [ Druid-ConnectionPool-Create-345197249:433 ] - [ ERROR ]  create connection error, url: jdbc:mysql://192.168.120.244:3306/aes?characterEncoding=utf-8, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'JackWei' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor29.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1425)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1481)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1998)
2018-12-25 10:04:00  [ Druid-ConnectionPool-Create-345197249:435 ] - [ ERROR ]  create connection error, url: jdbc:mysql://192.168.120.244:3306/aes?characterEncoding=utf-8, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'JackWei' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor29.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1425)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1481)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1998)
2018-12-25 10:04:00  [ Druid-ConnectionPool-Create-345197249:438 ] - [ ERROR ]  create connection error, url: jdbc:mysql://192.168.120.244:3306/aes?characterEncoding=utf-8, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'JackWei' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor29.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1425)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1481)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1998)
2018-12-25 10:04:00  [ Druid-ConnectionPool-Create-345197249:441 ] - [ ERROR ]  create connection error, url: jdbc:mysql://192.168.120.244:3306/aes?characterEncoding=utf-8, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'JackWei' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor29.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1425)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1481)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1998)
2018-12-25 10:04:00  [ Druid-ConnectionPool-Create-345197249:443 ] - [ ERROR ]  create connection error, url: jdbc:mysql://192.168.120.244:3306/aes?characterEncoding=utf-8, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'JackWei' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor29.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1425)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1481)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1998)
2018-12-25 10:04:00  [ Druid-ConnectionPool-Create-345197249:445 ] - [ ERROR ]  create connection error, url: jdbc:mysql://192.168.120.244:3306/aes?characterEncoding=utf-8, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'JackWei' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor29.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1425)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1481)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1998)
2018-12-25 10:04:00  [ Druid-ConnectionPool-Create-345197249:448 ] - [ ERROR ]  create connection error, url: jdbc:mysql://192.168.120.244:3306/aes?characterEncoding=utf-8, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'JackWei' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor29.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1425)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1481)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1998)
2018-12-25 10:04:00  [ Druid-ConnectionPool-Create-345197249:450 ] - [ ERROR ]  create connection error, url: jdbc:mysql://192.168.120.244:3306/aes?characterEncoding=utf-8, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'JackWei' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor29.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1425)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1481)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1998)
2018-12-25 10:04:00  [ Druid-ConnectionPool-Create-345197249:453 ] - [ ERROR ]  create connection error, url: jdbc:mysql://192.168.120.244:3306/aes?characterEncoding=utf-8, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'JackWei' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor29.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1425)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1481)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1998)
2018-12-25 10:04:00  [ Druid-ConnectionPool-Create-345197249:457 ] - [ ERROR ]  create connection error, url: jdbc:mysql://192.168.120.244:3306/aes?characterEncoding=utf-8, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'JackWei' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor29.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1425)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1481)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1998)
2018-12-25 10:04:00  [ Druid-ConnectionPool-Create-345197249:459 ] - [ ERROR ]  create connection error, url: jdbc:mysql://192.168.120.244:3306/aes?characterEncoding=utf-8, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'JackWei' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor29.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1425)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1481)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1998)
2018-12-25 10:04:00  [ Druid-ConnectionPool-Create-345197249:462 ] - [ ERROR ]  create connection error, url: jdbc:mysql://192.168.120.244:3306/aes?characterEncoding=utf-8, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'JackWei' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor29.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1425)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1481)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1998)
2018-12-25 10:04:00  [ Druid-ConnectionPool-Create-345197249:501 ] - [ ERROR ]  create connection error, url: jdbc:mysql://192.168.120.244:3306/aes?characterEncoding=utf-8, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'JackWei' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor29.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1425)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1481)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1998)
2018-12-25 10:04:00  [ Druid-ConnectionPool-Create-345197249:505 ] - [ ERROR ]  create connection error, url: jdbc:mysql://192.168.120.244:3306/aes?characterEncoding=utf-8, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'JackWei' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor29.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1425)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1481)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1998)
2018-12-25 10:04:00  [ Druid-ConnectionPool-Create-345197249:510 ] - [ ERROR ]  create connection error, url: jdbc:mysql://192.168.120.244:3306/aes?characterEncoding=utf-8, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'JackWei' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2370)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2154)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor29.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1425)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1481)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1998)
2018-12-25 10:05:00  [ pool-1-thread-1:0 ] - [ INFO ]  {dataSource-1} inited
2018-12-25 10:05:02  [ pool-1-thread-1:2811 ] - [ ERROR ]  发送失败
2018-12-25 10:05:02  [ pool-1-thread-1:2812 ] - [ ERROR ]  Couldn't connect to host, port: smtp.163.com, 25; timeout -1
2018-12-25 10:05:03  [ pool-1-thread-1:2935 ] - [ ERROR ]  发送失败
2018-12-25 10:05:03  [ pool-1-thread-1:2935 ] - [ ERROR ]  Couldn't connect to host, port: smtp.163.com, 25; timeout -1
2018-12-25 10:05:03  [ pool-1-thread-1:2957 ] - [ ERROR ]  发送失败
2018-12-25 10:05:03  [ pool-1-thread-1:2957 ] - [ ERROR ]  Couldn't connect to host, port: smtp.163.com, 25; timeout -1
2018-12-25 10:05:03  [ pool-1-thread-1:2987 ] - [ ERROR ]  发送失败
2018-12-25 10:05:03  [ pool-1-thread-1:2987 ] - [ ERROR ]  Couldn't connect to host, port: smtp.163.com, 25; timeout -1
2018-12-25 10:06:09  [ pool-1-thread-1:69164 ] - [ INFO ]  发送成功
2018-12-25 10:06:17  [ pool-1-thread-1:76945 ] - [ INFO ]  发送成功
2018-12-25 10:06:21  [ pool-1-thread-1:81538 ] - [ INFO ]  发送成功
2018-12-25 10:06:24  [ pool-1-thread-1:84544 ] - [ INFO ]  发送成功
2018-12-25 10:07:04  [ pool-1-thread-1:123945 ] - [ INFO ]  发送成功
2018-12-25 10:07:11  [ pool-1-thread-1:131250 ] - [ INFO ]  发送成功
2018-12-25 10:07:23  [ pool-1-thread-1:143126 ] - [ INFO ]  发送成功
2018-12-25 14:20:00  [ pool-1-thread-1:0 ] - [ INFO ]  {dataSource-1} inited
2018-12-25 14:20:04  [ pool-1-thread-1:4325 ] - [ INFO ]  发送成功
2018-12-25 14:20:06  [ pool-1-thread-1:5935 ] - [ INFO ]  发送成功
2018-12-25 14:20:07  [ pool-1-thread-1:7062 ] - [ INFO ]  发送成功
2018-12-25 14:20:20  [ pool-1-thread-1:19929 ] - [ INFO ]  发送成功
2018-12-25 15:49:00  [ pool-1-thread-1:0 ] - [ INFO ]  {dataSource-1} inited
2018-12-25 15:49:04  [ pool-1-thread-1:4317 ] - [ ERROR ]  发送失败
2018-12-25 15:49:04  [ pool-1-thread-1:4318 ] - [ ERROR ]  Couldn't connect to host, port: smtp.163.com, 25; timeout -1
2018-12-25 15:49:04  [ pool-1-thread-1:4697 ] - [ ERROR ]  发送失败
2018-12-25 15:49:04  [ pool-1-thread-1:4697 ] - [ ERROR ]  Couldn't connect to host, port: smtp.163.com, 25; timeout -1
2018-12-25 15:49:05  [ pool-1-thread-1:4831 ] - [ ERROR ]  发送失败
2018-12-25 15:49:05  [ pool-1-thread-1:4831 ] - [ ERROR ]  Couldn't connect to host, port: smtp.163.com, 25; timeout -1
2018-12-25 15:49:05  [ pool-1-thread-1:4878 ] - [ ERROR ]  发送失败
2018-12-25 15:49:05  [ pool-1-thread-1:4878 ] - [ ERROR ]  Couldn't connect to host, port: smtp.163.com, 25; timeout -1
2018-12-25 15:50:00  [ pool-1-thread-1:60208 ] - [ ERROR ]  发送失败
2018-12-25 15:50:00  [ pool-1-thread-1:60208 ] - [ ERROR ]  550 User has no permission

2018-12-25 15:50:00  [ pool-1-thread-1:60556 ] - [ ERROR ]  发送失败
2018-12-25 15:50:00  [ pool-1-thread-1:60556 ] - [ ERROR ]  550 User has no permission

2018-12-25 15:50:01  [ pool-1-thread-1:60843 ] - [ ERROR ]  发送失败
2018-12-25 15:50:01  [ pool-1-thread-1:60844 ] - [ ERROR ]  550 User has no permission

2018-12-25 15:50:01  [ pool-1-thread-1:61161 ] - [ ERROR ]  发送失败
2018-12-25 15:50:01  [ pool-1-thread-1:61164 ] - [ ERROR ]  550 User has no permission

2018-12-25 15:51:00  [ pool-1-thread-1:120055 ] - [ ERROR ]  发送失败
2018-12-25 15:51:00  [ pool-1-thread-1:120055 ] - [ ERROR ]  550 User has no permission

2018-12-25 15:51:00  [ pool-1-thread-1:120359 ] - [ ERROR ]  发送失败
2018-12-25 15:51:00  [ pool-1-thread-1:120359 ] - [ ERROR ]  550 User has no permission

2018-12-25 15:51:00  [ pool-1-thread-1:120651 ] - [ ERROR ]  发送失败
2018-12-25 15:51:00  [ pool-1-thread-1:120651 ] - [ ERROR ]  550 User has no permission

2018-12-25 15:51:01  [ pool-1-thread-1:120930 ] - [ ERROR ]  发送失败
2018-12-25 15:51:01  [ pool-1-thread-1:120930 ] - [ ERROR ]  550 User has no permission

2018-12-25 15:53:00  [ pool-1-thread-1:0 ] - [ INFO ]  {dataSource-1} inited
2018-12-25 15:53:01  [ pool-1-thread-1:1245 ] - [ INFO ]  发送成功
2018-12-25 15:53:02  [ pool-1-thread-1:2521 ] - [ INFO ]  发送成功
2018-12-25 15:53:05  [ pool-1-thread-1:4912 ] - [ INFO ]  发送成功
2018-12-25 15:53:05  [ pool-1-thread-1:5671 ] - [ INFO ]  发送成功
2018-12-25 15:56:00  [ pool-1-thread-1:1 ] - [ INFO ]  {dataSource-1} inited
2018-12-25 15:56:02  [ pool-1-thread-1:2133 ] - [ ERROR ]  发送失败
2018-12-25 15:56:02  [ pool-1-thread-1:2134 ] - [ ERROR ]  550 User has no permission

2018-12-25 15:56:04  [ pool-1-thread-1:4716 ] - [ ERROR ]  发送失败
2018-12-25 15:56:04  [ pool-1-thread-1:4716 ] - [ ERROR ]  550 User has no permission

2018-12-25 15:56:07  [ pool-1-thread-1:7632 ] - [ ERROR ]  发送失败
2018-12-25 15:56:07  [ pool-1-thread-1:7632 ] - [ ERROR ]  550 User has no permission

2018-12-25 15:56:09  [ pool-1-thread-1:9735 ] - [ ERROR ]  发送失败
2018-12-25 15:56:09  [ pool-1-thread-1:9735 ] - [ ERROR ]  550 User has no permission

2018-12-25 16:04:00  [ pool-1-thread-1:0 ] - [ INFO ]  {dataSource-1} inited
2018-12-25 16:04:21  [ pool-1-thread-1:21455 ] - [ ERROR ]  发送失败
2018-12-25 16:04:21  [ pool-1-thread-1:21455 ] - [ ERROR ]  Couldn't connect to host, port: smtp.163.com, 25; timeout -1
2018-12-25 16:06:00  [ pool-1-thread-1:0 ] - [ INFO ]  {dataSource-1} inited
2018-12-25 16:06:40  [ pool-1-thread-1:40681 ] - [ ERROR ]  发送失败
2018-12-25 16:06:40  [ pool-1-thread-1:40681 ] - [ ERROR ]  550 User has no permission

2018-12-25 16:06:41  [ pool-1-thread-1:41028 ] - [ ERROR ]  发送失败
2018-12-25 16:06:41  [ pool-1-thread-1:41028 ] - [ ERROR ]  550 User has no permission

2018-12-25 16:06:41  [ pool-1-thread-1:41399 ] - [ ERROR ]  发送失败
2018-12-25 16:06:41  [ pool-1-thread-1:41399 ] - [ ERROR ]  550 User has no permission

2018-12-25 16:06:41  [ pool-1-thread-1:41741 ] - [ ERROR ]  发送失败
2018-12-25 16:06:41  [ pool-1-thread-1:41741 ] - [ ERROR ]  550 User has no permission

2018-12-25 16:10:00  [ pool-1-thread-1:0 ] - [ INFO ]  {dataSource-1} inited
2018-12-25 16:10:07  [ pool-1-thread-1:7907 ] - [ INFO ]  发送成功
